services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=omnicare_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:pass@db:5432/omnicare_db
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://admin:pass@db:5432/omnicare_db  # 👈 أضف هذا السطر هنا ليتمكن الـ Worker من قراءة الـ Schema

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://admin:pass@db:5432/omnicare_db  # 👈 أضف هذا السطر هنا أيضاً لسلامة التهيئات المبدئية للـ Beat

volumes:
  postgres_data: