# Generated by Django 5.0 on 2026-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='الجنس')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='السجل الطبي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
