"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ubn!v7j2embgw45_r5&*ug%+wtok^h2!g-5=2fhx(j)a#l7ty)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.localhost']

# Application definition

SHARED_APPS = [
    'daphne',
    'django_tenants', # يجب أن يكون أول تطبيق
    'apps.platform_admin.tenants', # تطبيق إدارة المستشفيات الذي أنشأناه
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',

]

# تطبيقات المستشفى (تُنشأ جداولها لكل مستشفى على حدة)
TENANT_APPS = [
    'django.contrib.auth', # ليكون لكل مشفى مستخدموه المستقلون
    'django.contrib.contenttypes',
    'apps.medical_core.patients',
    'apps.medical_core.appointments',
    'apps.medical_core.doctors',
    'apps.medical_core.chat',
    'apps.medical_core.notifications',
    'apps.medical_core.notifications.tasks',
    'apps.medical_core.communication',
    # هنا سنضيف لاحقاً medical_core.patients وغيرها
]

# دمج التطبيقات مع الحفاظ التام على الترتيب ومنع التكرار
INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'omnicare_db',
        'USER': 'admin',
        'PASSWORD': 'pass',
        'HOST': 'db',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TENANT_MODEL = 'tenants.Hospital' # 'اسم_التطبيق.اسم_الموديل'
TENANT_DOMAIN_MODEL = 'tenants.Domain'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('omnicare-redis-1', 6379)], # استخدم اسم الحاوية الذي ظهر في Docker لديك
        },
    },
}
# --- CELERY SETTINGS ---
# تحديد رابط الـ Redis كـ Broker (وسيط للمهام) و كمخزن للنتائج (Result Backend)
CELERY_BROKER_URL = 'redis://redis:6379/1'
CELERY_RESULT_BACKEND = 'redis://redis:6379/1'

# إعدادات الصيغ والوقت
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # سيعتمد على نفس التوقيت المحدد في مشروعك

# تفعيل نظام الجدولة الديناميكي عبر قاعدة البيانات
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'